import type { VolunteerEvent } from "@/types/volunteer/event";

export const ZAGREB_CENTER = {
  latitude: 45.815,
  longitude: 15.9819,
  latitudeDelta: 0.04,
  longitudeDelta: 0.04,
};

export const MOCK_MAP_EVENTS: VolunteerEvent[] = [
  {
    id: "evt-1",
    title: "Maksimir Park Cleanup",
    description: "Help us clean up Maksimir Park trails and pick up litter around the lake area.",
    category: "environment",
    tags: ["outdoor", "cleanup", "nature", "beginner-friendly"],
    address: "Maksimirski perivoj, Zagreb",
    latitude: 45.8269,
    longitude: 16.0184,
    startsAt: "2026-04-05T09:00:00Z",
    durationMinutes: 180,
    volunteersNeeded: 15,
    volunteersApplied: 8,
    points: 25,
    organizerName: "Zeleni Zagreb",
    organizerId: "",
    createdAt: "2026-03-20T12:00:00Z",
  },
  {
    id: "evt-2",
    title: "Reading at City Library",
    description: "Read stories to children at the city library Saturday morning program.",
    category: "education",
    tags: ["indoor", "kids", "reading", "weekend"],
    address: "Starčevićev trg 6, Zagreb",
    latitude: 45.8109,
    longitude: 15.9772,
    startsAt: "2026-04-06T10:00:00Z",
    durationMinutes: 120,
    volunteersNeeded: 5,
    volunteersApplied: 2,
    points: 15,
    organizerName: "Knjižnica Zagreb",
    organizerId: "",
    createdAt: "2026-03-21T10:00:00Z",
  },
  {
    id: "evt-3",
    title: "Dog Shelter Morning Walk",
    description: "Walk and socialize shelter dogs at Dumovec animal shelter.",
    category: "animals",
    tags: ["outdoor", "dogs", "morning", "beginner-friendly"],
    address: "Dumovec 71, Zagreb",
    latitude: 45.8363,
    longitude: 15.9573,
    startsAt: "2026-04-07T08:00:00Z",
    durationMinutes: 120,
    volunteersNeeded: 10,
    volunteersApplied: 6,
    points: 20,
    organizerName: "Azil Dumovec",
    organizerId: "",
    createdAt: "2026-03-22T08:00:00Z",
  },
  {
    id: "evt-4",
    title: "Elderly Home Visit",
    description: "Spend time with elderly residents — board games, conversation, and company.",
    category: "social",
    tags: ["indoor", "elderly", "companionship", "afternoon"],
    address: "Trnjanska cesta 99, Zagreb",
    latitude: 45.7985,
    longitude: 15.9885,
    startsAt: "2026-04-08T14:00:00Z",
    durationMinutes: 150,
    volunteersNeeded: 8,
    volunteersApplied: 3,
    points: 20,
    organizerName: "Caritas Zagreb",
    organizerId: "",
    createdAt: "2026-03-23T14:00:00Z",
  },
  {
    id: "evt-5",
    title: "Community Food Drive",
    description: "Sort and pack donated food supplies for families in need.",
    category: "community",
    tags: ["indoor", "food", "teamwork", "physical"],
    address: "Heinzelova 66, Zagreb",
    latitude: 45.8198,
    longitude: 16.0025,
    startsAt: "2026-04-09T11:00:00Z",
    durationMinutes: 240,
    volunteersNeeded: 20,
    volunteersApplied: 12,
    points: 30,
    organizerName: "Crveni Križ Zagreb",
    organizerId: "",
    createdAt: "2026-03-24T11:00:00Z",
  },
  {
    id: "evt-6",
    title: "Jarun Lake Shore Cleanup",
    description: "Clean up trash and debris along the Jarun lake walking paths.",
    category: "environment",
    tags: ["outdoor", "cleanup", "lake", "weekend"],
    address: "Jarun, Zagreb",
    latitude: 45.7825,
    longitude: 15.9255,
    startsAt: "2026-04-12T09:00:00Z",
    durationMinutes: 180,
    volunteersNeeded: 12,
    volunteersApplied: 4,
    points: 25,
    organizerName: "Zeleni Zagreb",
    organizerId: "",
    createdAt: "2026-03-25T09:00:00Z",
  },
  {
    id: "evt-7",
    title: "Tutoring High Schoolers",
    description: "Math and science tutoring for high school students preparing for exams.",
    category: "education",
    tags: ["indoor", "math", "science", "teens"],
    address: "Kačićeva 9, Zagreb",
    latitude: 45.8098,
    longitude: 15.9676,
    startsAt: "2026-04-10T16:00:00Z",
    durationMinutes: 90,
    volunteersNeeded: 6,
    volunteersApplied: 1,
    points: 15,
    organizerName: "Učilište Zagreb",
    organizerId: "",
    createdAt: "2026-03-26T16:00:00Z",
  },
];
